plugin:
  webapp: no
  static: no
  description: |
    TO-DO
  dependencies:
    - urllib
channels_params:
  token:
    name: 'App Token (Testing)'
    placeholder: 'Plain text'
    type: string
    default: ''
  page_id:
    name: 'Facebook page id (url for later)'
    placeholder: 'Plain text'
    type: string
    default: ''
  number_post:
    name: 'Number of post in each slide'
    placeholder: 'Number of post'
    type: int
    default: 3
    min: 1
  duration:
    name: 'Slide duration in seconds'
    placeholder: 'Slide duration in seconds'
    type: int
    default: 10
    min: 1

