plugin:
  webapp: no
  static: yes
  description: |
    This plugin displays informations about a GitHub repository/organization such as the number of commits, the top contributors, the opened and closed issues, the new releases and some stats.
  dependencies:
    - github
channels_params:
  token:
    name: 'User or organization Token'
    placeholder: 'Plain text'
    type: string
    default: ''
  repo_url:
    name: 'Github repository URL'
    placeholder: 'username/repository'
    type: string
    default: ''
  had_organization:
    name: 'Has an organization'
    type: bool
    default: no
  number_organizations:
    name: 'Number of last-updated repositories on each slide'
    placeholder: 'Number of last-updated repositories'
    type: int
    default: 3
    min: 1
    max: 4
  orga_url:
    name: 'Github organization URL'
    placeholder: 'organization'
    type: string
    default: ''
  disp_commits:
    name: 'Display commits'
    type: bool
    default: yes
  number_commits:
    name: 'Number of commits on each slide'
    placeholder: 'Number of post'
    type: int
    default: 3
    min: 1
    max: 4
  max_days_commit:
    name: 'Show the commit not older than ... days'
    placeholder: 'Show the commit not older than ... days'
    type: int
    default: 364
    min: 1
  disp_contributors:
    name: 'Display contributors'
    type: bool
    default: yes
  number_contributors:
    name: 'Number of contributors on each slide'
    placeholder: 'Number of contributors'
    type: int
    default: 3
    min: 1
    max: 5
  disp_issues:
    name: 'Display opened and closed issues'
    type: bool
    default: yes
  number_issues:
    name: 'Opened and closed issues on each slide'
    placeholder: 'Issues'
    type: int
    default: 3
    min: 1
    max: 4
  disp_releases:
    name: 'Display new releases'
    type: bool
    default: yes
  number_releases:
    name: 'Number of releases on each slide'
    placeholder: 'Number of releases'
    type: int
    default: 3
    min: 1
    max: 7
  disp_stat:
    name: 'Display general informations about the repository'
    type: bool
    default: yes
  duration:
    name: 'Slide duration in seconds'
    placeholder: 'Slide duration in seconds'
    type: int
    default: 10
    min: 1
